apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: tls-replicator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: tls-replicator
    app.kubernetes.io/part-of: tls-replicator
  name: tls-replicator