apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: replikator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: replikator
    app.kubernetes.io/part-of: replikator
  name: replikator