apiVersion: v1
kind: Service
metadata:
  name: replikator-metrics
  namespace: replikator
  labels:
    app.kubernetes.io/name: replikator
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/name: replikator
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080