apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tls-replicator
    app.kubernetes.io/part-of: tls-replicator
  name: controller-manager
  namespace: tls-replicator
