apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster
  namespace: cert-manager
spec:
  isCA: true
  secretName: cluster-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: Cluster CA
  secretTemplate:
    annotations:
      v1alpha1.tls-replicator.gpuninja.com/enabled: "true"
      v1alpha1.tls-replicator.gpuninja.com/replicated-keys: "ca.crt"